employees = [{"eid":1,"ename":"Stanislaus","gender":"Male","country":"Venezuela"},
{"eid":2,"ename":"Rowan","gender":"Male","country":"China"},
{"eid":3,"ename":"Jesus","gender":"Male","country":"Vietnam"},
{"eid":4,"ename":"Jobyna","gender":"Female","country":"France"},
{"eid":5,"ename":"Obed","gender":"Male","country":"Nigeria"},
{"eid":6,"ename":"Veronika","gender":"Female","country":"Poland"},
{"eid":7,"ename":"Curran","gender":"Male","country":"Nepal"},
{"eid":8,"ename":"Franciskus","gender":"Male","country":"Indonesia"},
{"eid":9,"ename":"Howie","gender":"Genderfluid","country":"Egypt"},
{"eid":10,"ename":"Monty","gender":"Male","country":"China"},
{"eid":11,"ename":"Parke","gender":"Male","country":"Indonesia"},
{"eid":12,"ename":"Base","gender":"Male","country":"Iraq"},
{"eid":13,"ename":"Kylie","gender":"Genderfluid","country":"Nicaragua"},
{"eid":14,"ename":"Merwin","gender":"Male","country":"France"},
{"eid":15,"ename":"Sheppard","gender":"Male","country":"Indonesia"},
{"eid":16,"ename":"Garth","gender":"Male","country":"Mexico"},
{"eid":17,"ename":"Milt","gender":"Male","country":"Poland"},
{"eid":18,"ename":"Annelise","gender":"Female","country":"Mexico"},
{"eid":19,"ename":"Jolene","gender":"Female","country":"Indonesia"},
{"eid":20,"ename":"Raynard","gender":"Male","country":"Bulgaria"},
{"eid":21,"ename":"Preston","gender":"Male","country":"Russia"},
{"eid":22,"ename":"Tudor","gender":"Bigender","country":"Zambia"},
{"eid":23,"ename":"Hamid","gender":"Male","country":"Nigeria"},
{"eid":24,"ename":"Nalani","gender":"Female","country":"Yemen"},
{"eid":25,"ename":"Opal","gender":"Female","country":"United States"},
{"eid":26,"ename":"Esteban","gender":"Male","country":"Portugal"},
{"eid":27,"ename":"Wylie","gender":"Male","country":"Philippines"},
{"eid":28,"ename":"Neala","gender":"Female","country":"Ukraine"},
{"eid":29,"ename":"Eberto","gender":"Male","country":"Russia"},
{"eid":30,"ename":"Charin","gender":"Genderqueer","country":"China"},
{"eid":31,"ename":"Elfrida","gender":"Female","country":"China"},
{"eid":32,"ename":"Cyrille","gender":"Male","country":"China"},
{"eid":33,"ename":"Libbi","gender":"Genderqueer","country":"Indonesia"},
{"eid":34,"ename":"Rosanna","gender":"Female","country":"China"},
{"eid":35,"ename":"Silvie","gender":"Female","country":"Indonesia"},
{"eid":36,"ename":"Lynna","gender":"Female","country":"Philippines"},
{"eid":37,"ename":"Marje","gender":"Female","country":"Philippines"},
{"eid":38,"ename":"Bettine","gender":"Female","country":"Philippines"},
{"eid":39,"ename":"Wyatan","gender":"Male","country":"France"},
{"eid":40,"ename":"Cammy","gender":"Male","country":"Portugal"},
{"eid":41,"ename":"Patty","gender":"Male","country":"France"},
{"eid":42,"ename":"Paquito","gender":"Male","country":"Philippines"},
{"eid":43,"ename":"Thane","gender":"Male","country":"China"},
{"eid":44,"ename":"Cherise","gender":"Female","country":"South Africa"},
{"eid":45,"ename":"Jeffrey","gender":"Non-binary","country":"Philippines"},
{"eid":46,"ename":"Clarine","gender":"Female","country":"Micronesia"},
{"eid":47,"ename":"Irvine","gender":"Male","country":"Tajikistan"},
{"eid":48,"ename":"Sean","gender":"Female","country":"Morocco"},
{"eid":49,"ename":"Susannah","gender":"Female","country":"China"},
{"eid":50,"ename":"Selina","gender":"Female","country":"Greece"},
{"eid":51,"ename":"Ekaterina","gender":"Female","country":"Argentina"},
{"eid":52,"ename":"Petrina","gender":"Female","country":"Russia"},
{"eid":53,"ename":"Charmane","gender":"Female","country":"China"},
{"eid":54,"ename":"Evelyn","gender":"Female","country":"Indonesia"},
{"eid":55,"ename":"Joye","gender":"Female","country":"Greenland"},
{"eid":56,"ename":"Brittni","gender":"Female","country":"China"},
{"eid":57,"ename":"Delora","gender":"Female","country":"Indonesia"},
{"eid":58,"ename":"Frans","gender":"Polygender","country":"Argentina"},
{"eid":59,"ename":"Domenico","gender":"Non-binary","country":"South Korea"},
{"eid":60,"ename":"Mirelle","gender":"Female","country":"Russia"},
{"eid":61,"ename":"Gail","gender":"Non-binary","country":"Honduras"},
{"eid":62,"ename":"Berty","gender":"Female","country":"Portugal"},
{"eid":63,"ename":"Donovan","gender":"Male","country":"Venezuela"},
{"eid":64,"ename":"Waylin","gender":"Male","country":"Indonesia"},
{"eid":65,"ename":"Nan","gender":"Female","country":"Czech Republic"},
{"eid":66,"ename":"Ruby","gender":"Female","country":"Egypt"},
{"eid":67,"ename":"Perceval","gender":"Agender","country":"Finland"},
{"eid":68,"ename":"Winne","gender":"Genderqueer","country":"Indonesia"},
{"eid":69,"ename":"Otis","gender":"Male","country":"Pakistan"},
{"eid":70,"ename":"Jarad","gender":"Male","country":"Bolivia"},
{"eid":71,"ename":"Valera","gender":"Female","country":"Nigeria"},
{"eid":72,"ename":"Trey","gender":"Bigender","country":"Thailand"},
{"eid":73,"ename":"Vaughn","gender":"Male","country":"Sudan"},
{"eid":74,"ename":"Cyb","gender":"Female","country":"China"},
{"eid":75,"ename":"Ancell","gender":"Male","country":"China"},
{"eid":76,"ename":"Anthea","gender":"Female","country":"Mexico"},
{"eid":77,"ename":"Midge","gender":"Female","country":"Jamaica"},
{"eid":78,"ename":"Theobald","gender":"Male","country":"Russia"},
{"eid":79,"ename":"Nye","gender":"Male","country":"Iran"},
{"eid":80,"ename":"Conn","gender":"Male","country":"Slovenia"},
{"eid":81,"ename":"Karon","gender":"Female","country":"Greece"},
{"eid":82,"ename":"Neron","gender":"Male","country":"Russia"},
{"eid":83,"ename":"Lucio","gender":"Male","country":"Poland"},
{"eid":84,"ename":"Jakie","gender":"Genderfluid","country":"Germany"},
{"eid":85,"ename":"Sheilah","gender":"Female","country":"China"},
{"eid":86,"ename":"Travers","gender":"Male","country":"Portugal"},
{"eid":87,"ename":"Francis","gender":"Male","country":"Indonesia"},
{"eid":88,"ename":"Tyson","gender":"Male","country":"China"},
{"eid":89,"ename":"Kyle","gender":"Male","country":"China"},
{"eid":90,"ename":"Arabelle","gender":"Polygender","country":"Latvia"},
{"eid":91,"ename":"Saundra","gender":"Male","country":"Myanmar"},
{"eid":92,"ename":"Nicola","gender":"Female","country":"Japan"},
{"eid":93,"ename":"Lombard","gender":"Genderfluid","country":"Belarus"},
{"eid":94,"ename":"Guenna","gender":"Non-binary","country":"Brazil"},
{"eid":95,"ename":"Larisa","gender":"Female","country":"Poland"},
{"eid":96,"ename":"Vicki","gender":"Female","country":"Russia"},
{"eid":97,"ename":"Baxie","gender":"Non-binary","country":"Qatar"},
{"eid":98,"ename":"Maggy","gender":"Female","country":"Greece"},
{"eid":99,"ename":"Chantalle","gender":"Genderfluid","country":"Israel"},
{"eid":100,"ename":"Moria","gender":"Female","country":"Sudan"}]

male_emp_names = []
female_emp_names = []
for emp in employees:
    if emp['gender'] == 'Male':
        male_emp_names.append(emp['ename'])
    elif emp['gender'] == 'Female':
        female_emp_names.append(emp['ename'])

print(len(male_emp_names))
print(len(female_emp_names))